set_property IOSTANDARD LVCMOS33 [get_ports {a_n[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_n[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_n[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_n[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {abcdefgdec_n[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {abcdefgdec_n[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {abcdefgdec_n[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {abcdefgdec_n[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {abcdefgdec_n[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {abcdefgdec_n[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {abcdefgdec_n[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {abcdefgdec_n[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sp[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sp[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sp[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sp[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sp[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sp[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sp[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sp[0]}]
set_property PACKAGE_PIN V12 [get_ports {abcdefgdec_n[7]}]
set_property PACKAGE_PIN W12 [get_ports {abcdefgdec_n[6]}]
set_property PACKAGE_PIN W10 [get_ports {abcdefgdec_n[5]}]
set_property PACKAGE_PIN W11 [get_ports {abcdefgdec_n[4]}]
set_property PACKAGE_PIN V9 [get_ports {abcdefgdec_n[3]}]
set_property PACKAGE_PIN V10 [get_ports {abcdefgdec_n[2]}]
set_property PACKAGE_PIN V8 [get_ports {abcdefgdec_n[1]}]
set_property PACKAGE_PIN W8 [get_ports {abcdefgdec_n[0]}]
set_property PACKAGE_PIN AB11 [get_ports {a_n[3]}]
set_property PACKAGE_PIN AB10 [get_ports {a_n[2]}]
set_property PACKAGE_PIN AB9 [get_ports {a_n[1]}]
set_property PACKAGE_PIN AA8 [get_ports {a_n[0]}]
set_property PACKAGE_PIN M15 [get_ports {sp[7]}]
set_property PACKAGE_PIN H17 [get_ports {sp[6]}]
set_property PACKAGE_PIN H18 [get_ports {sp[5]}]
set_property PACKAGE_PIN H19 [get_ports {sp[4]}]
set_property PACKAGE_PIN F21 [get_ports {sp[3]}]
set_property PACKAGE_PIN H22 [get_ports {sp[2]}]
set_property PACKAGE_PIN G22 [get_ports {sp[1]}]
set_property PACKAGE_PIN F22 [get_ports {sp[0]}]
set_property PACKAGE_PIN Y10 [get_ports a]
set_property PACKAGE_PIN T18 [get_ports arst]
set_property PACKAGE_PIN AA9 [get_ports b]
set_property PACKAGE_PIN N15 [get_ports force_ccw]
set_property PACKAGE_PIN R18 [get_ports force_cw]
set_property PACKAGE_PIN AA11 [get_ports motor_ccw]
set_property PACKAGE_PIN Y11 [get_ports motor_cw]
set_property PACKAGE_PIN P16 [get_ports sync_rst]
create_clock -period 20.000 -name refclk -waveform {0.000 10.000} [get_ports refclk]
create_generated_clock -name {CRU_instance/clkdiv_0/Q[0]} -source [get_ports refclk] -divide_by 1 [get_pins {CRU_instance/clkdiv_0/mclk_cnt_reg[6]/Q}]
create_generated_clock -name {CRU_instance/rstsynch_0/PRESENT_STATE_reg[0]} -source [get_ports refclk] -divide_by 1 [get_pins CRU_instance/rstsynch_0/rst_s2_reg/Q]
create_generated_clock -name {pos_ctrl_instance/p_ctrl_instance/PRESENT_STATE[0]} -source [get_pins {CRU_instance/clkdiv_0/mclk_cnt_reg[6]/Q}] -divide_by 1 [get_pins {pos_ctrl_instance/p_ctrl_instance/PRESENT_STATE_reg[0]/Q}]
create_generated_clock -name pos_ctrl_instance/pos_meas_instance/count_down_en -source [get_ports refclk] -divide_by 1 [get_pins pos_ctrl_instance/pos_meas_instance/count_down_en_reg/Q]
create_generated_clock -name pos_ctrl_instance/pos_meas_instance/count_up_en -source [get_ports refclk] -divide_by 1 [get_pins pos_ctrl_instance/pos_meas_instance/count_up_en_reg/Q]

set_property PACKAGE_PIN Y9 [get_ports refclk]
set_property IOSTANDARD LVCMOS33 [get_ports a]
set_property IOSTANDARD LVCMOS33 [get_ports arst]
set_property IOSTANDARD LVCMOS33 [get_ports b]
set_property IOSTANDARD LVCMOS33 [get_ports force_ccw]
set_property IOSTANDARD LVCMOS33 [get_ports force_cw]
set_property IOSTANDARD LVCMOS33 [get_ports motor_ccw]
set_property IOSTANDARD LVCMOS33 [get_ports motor_cw]
set_property IOSTANDARD LVCMOS33 [get_ports refclk]
set_property IOSTANDARD LVCMOS33 [get_ports sync_rst]
